
---
- name: Run a user entered command
  hosts: nxos
  gather_facts: no
  connection: local
  vars:
    creds:
        host: nxswitches
        transport: cli
  vars_prompt:
    - name: "command"
      prompt: "Please type a command: "
      private: no

  tasks:
    - name: running user entered command
      nxos_command:
        commands: 
          #- show version
          - "{{ command }}"     
      register: cmd
   
    
    - name: gather facts 
      nxos_facts:
        gather_subset:
          - config
          
      register: configfacts
    - debug: 
        
        #var: cmd.stdout_lines
        msg: "TESTING: {{ cmd.stdout }}"
        
        
        
#    - debug:
#        var: vars
#      with_items:
#        - vars
#        - environment
#        - group_names
#        - groups
#        - hostvars
